# Generated by Django 2.0 on 2019-05-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_basicinformation', '0002_basicinformation_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='wechat',
            field=models.URLField(null=True),
        ),
    ]
