# Generated by Django 2.0 on 2019-05-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write_basicinformation', '0003_basicinformation_wechat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basicinformation',
            table='basicinformation',
        ),
    ]
