# Generated by Django 2.0 on 2019-05-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workexperience',
            table='workexperience',
        ),
    ]
