# Generated by Django 2.0 on 2019-05-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head_image',
            field=models.URLField(null=True),
        ),
    ]
