# Generated by Django 2.0 on 2019-05-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_blog', '0002_user_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_image',
            field=models.URLField(default='http://img4.duitang.com/uploads/item/201603/08/20160308055305_AiuTz.jpeg', null=True),
        ),
    ]
