# Generated by Django 2.0 on 2019-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_blog', '0003_auto_20190507_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_image',
            field=models.URLField(default='http://down.52pk.com/uploads/181029/5039_164551_8945.jpeg', null=True),
        ),
    ]
