# Generated by Django 2.0 on 2019-05-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_blog', '0004_auto_20190507_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_image',
            field=models.URLField(default='http://myheartsky.com/1557161400905.jpg', null=True),
        ),
    ]
