# Generated by Django 2.0 on 2019-05-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_blog', '0005_auto_20190507_0207'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usershow',
            table='usershow',
        ),
    ]
