# Generated by Django 2.0 on 2019-05-22 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_blog', '0006_auto_20190520_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershow',
            name='id',
        ),
        migrations.AlterField(
            model_name='usershow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
