# Generated by Django 2.0 on 2019-06-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click_Num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('num', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'clicknumber',
            },
        ),
    ]
