# Generated by Django 2.0 on 2019-06-24 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('click_num', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click_num',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
