# Generated by Django 2.0 on 2019-05-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_readnum'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article_readnum',
            table='article_readnum',
        ),
    ]
