# Generated by Django 2.0 on 2019-05-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190520_0038'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AlterModelTable(
            name='articlecategory',
            table='articlecategory',
        ),
    ]
