# Generated by Django 2.0 on 2019-05-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190511_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='link_url',
            new_name='link_to',
        ),
    ]
