# Generated by Django 2.0 on 2019-05-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190511_0038'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='banner',
        ),
    ]
